#!/bin/sh
echo "PHP selecionado: $1"

if [ $1 ]; then

    YML_FILE="./docker-compose-php$1.yml";

    echo "docker-compose selecionado: $YML_FILE";

    exec docker-compose -f $YML_FILE up -d
else

    echo "Erro: Versão PHP não informada "

fi

